### ISSUE TITLE
dark theme glitched on android 4.4

### ISSUE THREAD

**Issue by lordpacco** [cSploit/android#261] opened 2015-09-22 05:31 UTC
I'm using android kitkat on the device lg v400 and the dark theme is glitched (some elements are black and others white) 
i already tried cleaning and reinstalling the app but it didnt solve the problem
![Uploading Screenshot_2015-09-22-02-27-15.png…]

**Comment by Tajnymag** [comment] 2015-09-22 05:56
This is a duplicate. Original issue: [#258] (https://github.com/cSploit/android/issues/258)

**Comment by tux-mind** [comment] 2015-09-24 13:02
duplicate of #258 

thanks @Tajnymag

**Closed by tux-mind** 2015-09-24 13:02 UTC
