### ISSUE TITLE
Network discovery failed 

### ISSUE THREAD

**Issue by Foul** [cSploit/android#454] opened 2015-10-19 07:29 UTC
Can't initialize any interface 

Nexus 9 Android 6.0 rooted 
SuperSu 2.52
Busybox 1.23.2
Csploit 1.7.0unstable+10c621c
No logs

**Comment by gainan** [comment] 2015-10-19 09:52
@Foul , we need logs to see what's going on. See how gather them: http://forum.xda-developers.com/showthread.php?t=1726238
On the other hand, if you could post the output of the following command would be very useful:
>ip a; ip r

thank you!

**Comment by Tajnymag** [comment] 2015-10-19 10:01
Also happens to me on CM12.1. [Here](http://pastebin.com/k79WntPB) is my log with device details.

**Comment by gainan** [comment] 2015-10-19 10:20
Thank you for the logs @Tajnymag , same problem than #448 . It should be fixed on the nightly.

**Comment by Tajnymag** [comment] 2015-10-19 15:07
@gainan I've just installed latest nigthly build, but I get the same error :-(

**Comment by Tajnymag** [comment] 2015-10-19 15:12
@gainan Here is output of "in a; ip r" 
http://pastebin.com/VWQnb0j9

**Comment by PTZema** [comment] 2015-10-24 13:31
With last nightly the network discovery don't work
Here the catlog http://pastebin.com/0JCys7Et
Cm 12.1
Lg l90 d405n

**Closed** 2015-10-29 15:02 UTC
Labels: more info required

**Comment by gainan** [comment] 2015-10-29 15:06
please, install today's nightly and see if the problem is fixed.

**Comment by Foul** [comment] 2015-10-29 15:36
fixed for me.
Nexus 9 Android 6.0
