### ISSUE TITLE
cSploitClient - connect_unix: connect: Connection refused

### ISSUE THREAD

**Issue by 0MazaHacka0** [cSploit/android#145] opened 2015-04-14 07:43 UTC
When I start cSploit, i see in logcat this message. I think because of this i dont have launch option in menu, and daemon dont connect. Android 4.4.4 (Full busybox, root).

**Comment by sorano** [comment] 2015-09-24 14:54
Duplicate of #205 
Try the latest version.

**Closed by sorano** 2015-09-24 14:54 UTC
