### ISSUE TITLE
ruby and gems for msf issues

### ISSUE THREAD

**Issue by uranium-waffles** [cSploit/android#157] opened 2015-04-24 02:33 UTC
Wondering If I can manually install the Metasploit framework to csploit or install the ruby gems manually.

**Comment by uranium-waffles** [comment] 2015-04-24 03:57
@tux-mind can you help me? I've gone through countless amounts of posts trying to find it.

**Comment by sorano** [comment] 2015-09-24 11:47
Duplicate of #205

**Closed by sorano** 2015-09-24 11:47 UTC
