### ISSUE TITLE
Metasploit RPCD - Process wont start - XT1032

### ISSUE THREAD

**Issue by Qu1cksnap** [cSploit/android#178] opened 2015-05-28 10:53 UTC
Hi,
The metasploit RPCD of csploit wont start on moto g XT1032. Android lollipop

**Comment by Systemad** [comment] 2015-05-28 13:08
It depends on the cpu, it should take to to 5 min (for me on htc one m7)

**Comment by Qu1cksnap** [comment] 2015-05-28 14:39
Even if i get the prompt saying that the process wont start? Also i shoud have include this is my original post. I also get prompt with an error messages when trying to download the latest Ruby updates. Thanks for the quick reply and awesome app! You'v got my like xD

**Comment by Qu1cksnap** [comment] 2015-05-28 14:43
*cannot start process*(metasploit rpcd) and *an error as occured while downloading the update* (ruby update) are the 2 error messages i get. Should i post a log somewhere with my devices spec? Thanks again

**Comment by Systemad** [comment] 2015-05-28 19:26
Log cat is not needed, the metasploit package seems to be broken. We just have to wait until @tux-mind fixes it. (He's very busy)

**Comment by PixelPips** [comment] 2015-06-11 19:36
I have exactly the same issue: can't start metasploit or download Ruby.

The application appears to be working for the most part though.

**Comment by sorano** [comment] 2015-09-24 11:59
Duplicate of #205
Try the latest version.

**Closed by sorano** 2015-09-24 11:59 UTC
