### ISSUE TITLE
core 1.0.5 install result on heart fail

### ISSUE THREAD

**Issue by setlec** [cSploit/android#232] opened 2015-09-07 14:59 UTC
So I've installed csploit  on my smt230 rooted but I can't  install  the csploit  core tool I'm using the default os 4.4.x from Samsung a and rooted with kingoroot.  I've got busybox installed with busybox  free app. Any suggestions that could enable me to  install  the core tool?

**Comment by DeveloppSoft** [comment] 2015-09-07 15:30
Use supersu.
@tux-mind can you add a wiki page forme thé core, please

**Comment by setlec** [comment] 2015-09-07 15:36
Thank you very much for your reply!

**Comment by gainan** [comment] 2015-09-19 20:04
@setlec did you manage to install the core tools or are you still having this problem?
close the issue if the problem is solved, or provide the exact steps to reproduce the problem, thank you!

**Comment by setlec** [comment] 2015-09-19 20:46
i've managed to install core tools but Csploit doesn't work that well but that's another issue.

**Comment by sorano** [comment] 2015-09-24 12:59
@setlec make sure you have supersu and busybox installed then you should not encounter the heart attack error. Seems like it is connected to kingoroot.

**Closed by sorano** 2015-09-24 12:59 UTC
