### ISSUE TITLE
Metasploit update issue / HTC One m7

### ISSUE THREAD

**Issue by kdotkdot** [cSploit/android#184] opened 2015-06-11 00:00 UTC
After i've downloaded Metasploit, the installation seems to be a andless loop. Current OS: Cyanogen Mod 12-20141205-UNOFFICIAL-m7.

**Comment by nerunexus** [comment] 2015-06-16 05:32
I will concure.  The m7 installs core and MFS but the Ruby gems install never completes. I'm on a cm12 based rom as well. For what it's worth dsploit works on stock.

**Comment by sorano** [comment] 2015-09-24 11:53
Duplicate of #205

**Closed by sorano** 2015-09-24 11:53 UTC
