### ISSUE TITLE
metasploit framework fails to install when installing gems for MSF

### ISSUE THREAD

**Issue by cesararduino** [cSploit/android#148] opened 2015-04-18 14:27 UTC
I have a moto g 2014 with rooted lollipop 5.0.2 using SuperSU as my app to control root permission. When I open csploit 1.5.3 for the first time, the core updates fine, the ruby seems to update fine too. But when its time to update the metasploit framework, it fails when installing gems. Then I try to start metasploit but it says "cannot start process". Some have had this issue fixed with the latest updates but my issue continues.BTW, I did grant root permission to csploit. Any ideas on how to fix this?

**Comment by sorano** [comment] 2015-09-24 11:47
Duplicate of #205

**Closed by sorano** 2015-09-24 11:47 UTC
