### ISSUE TITLE
is cSploit compatible with android marshmallow?

### ISSUE THREAD

**Issue by hao19** [cSploit/android#507] opened 2015-11-19 21:38 UTC
I'm asking this question because ever since I updated to android marshmallow build MRA58R from android lollipop build LMY48M, cSploit fails to download metasploit framwork. The device that I am using is the nexus 6, unlocked, rooted, busybox installed

**Comment by PixelPips** [comment] 2015-11-21 23:08
I am having the same issue, I suggest editing your issue so that it meets their [requirements](https://github.com/cSploit/android/wiki/How-to-open-an-issue), or commenting on my issue with the same info.

**Comment by tux-mind** [comment] 2015-11-30 00:08
duplicate of #503 

fixed just now :wink:

**Closed by tux-mind** 2015-11-30 00:08 UTC
