### ISSUE TITLE
Randomly changes in the settings

### ISSUE THREAD

**Issue by ddych** [cSploit/android#256] opened 2015-09-21 12:07 UTC
If there is any change in the settings, and I scroll screen or exit the settings and open again, some switches change position by themselves. Version 1.5.4, Android 4.2.2

**Comment by tux-mind** [comment] 2015-09-21 13:27
@ddych please provide a logcat as I cannot reproduce the issue on my device.

thanks for the report :)

**Comment by sorano** [comment] 2015-09-27 08:13
User has not returned with any logs.
Closing this.

**Closed by sorano** 2015-09-27 08:13 UTC
Labels: more info required
