### ISSUE TITLE
MITM Session Hijack NEW BROWSER

### ISSUE THREAD

**Issue by h439098** [cSploit/android#373] opened 2015-10-05 10:55 UTC
Can someone add NEW browser for Session hijack module. Because now default browser is awful. I cant copy the address (sometimes needed) and I cant download files. It would be great to be able to download files or copy address directly. Or maybe some "option" to change default browser to another installed in the system. I think many people need it. Thanks.

**Comment by gainan** [comment] 2015-10-05 11:31
it's not a bad idea @h439098 , the only problem I see is to load the sniffed cookie on an external browser, maybe too complicated for little gain. Would you mind to elaborate on why you can't download files from the current browser?

What if we improve the current one? write here the features it should have.

**Comment by h439098** [comment] 2015-10-05 12:43
I don't know why I cant download files. For example when I trying to download .DOC file (directly http://someadress.com/example.doc) it opens blank "white" page. And its all. No download and no other reactions.
It would be great to improve the browser. Features : 
Downloading files (maybe problem just with MS Office documents)
Copying, editing the address
Interactions (copying) with the links on the page (The same like second point but maybe someone needed)

Feature for MITM module : 
Automatically adding the NAME of the "router" (WiFi) to the name of the hijacked session. (So you can always choose right "session" for right router)

**Comment by h439098** [comment] 2015-10-05 13:06
Ouch ... Just realized why (maybe) I cant download some files. Its about redirection (maybe not :) ). I think there is no auto redirection. So its feature too : 
Auto redirection

**Comment by h439098** [comment] 2015-10-05 13:17
And now I find the problem. Its really about auto redirection (that doesn't exist in this browser) and there is problem with IFRAME objects (browser not displaying the iframes ?).

**Comment by fat-tire** [comment] 2015-10-06 04:33
Try the changes in the above-referenced commit.  Cheers!

**Comment by h439098** [comment] 2015-10-06 13:11
Sorry, but I'm new at GitHub. So how I can use this commit without compiling all the program by myself. If I will download nightly build, it will be there ?

**Comment by sorano** [comment] 2015-10-06 13:21
@h439098  No, that pull request has not been merged to master yet.
You will need to compile it yourself for now

**Comment by fat-tire** [comment] 2015-10-07 04:11
Hopefully we'll have it in tomorrow...

**Comment by tux-mind** [comment] 2015-10-07 11:33
@h439098 please try out the nightly tomorrow ( after 00:00 of dubai ), we have merge that feature right now.

let us known if the problem is solved :wink: 

compliments to @fat-tire  :blush:

**Comment by fat-tire** [comment] 2015-10-08 03:31
So yeah-- new URL bar, copy/paste and enter new links... pinch-to-zoom is fixed. Also, I just tried a http://goo.gl/SOMETHING link and it did redirect properly as well.

It's not a full browser, so don't expect it to support everything a browser does.  If there is more required than what's there, open a new bug.  The file to edit is [HijackerWebView.java](https://github.com/cSploit/android/blob/develop/cSploit/src/org/csploit/android/plugins/mitm/hijacker/HijackerWebView.java), which, incidentally, is an activity not a webview.  But whatevs.

**Comment by h439098** [comment] 2015-10-08 12:10
Yep, all is good. Thanks you. But there one more request - iframe. Can u do something, so iframes will work ? Because I just tested iframe object and its not worked. Just blank element (page).

**Comment by gainan** [comment] 2015-10-30 09:02
@h439098 open a new issue for work on the iframes problem if you don't mind :)

**Closed by gainan** 2015-10-30 09:02 UTC
Labels: enhancement
