### ISSUE TITLE
Update Ruby error

### ISSUE THREAD

**Issue by maximumbr** [cSploit/android#142] opened 2015-04-07 22:18 UTC
Galaxy s4 i9505g google edition 4.4.4 update ruby error.
"An error occurred while downloading the update."

**Comment by TheNormalnij** [comment] 2015-04-09 19:28
Explay A500 4.2. same error

**Comment by akremche** [comment] 2015-04-12 04:13
the same ERROR ( S4 I9505 )

**Comment by mandriva91** [comment] 2015-04-13 15:45
same here, s4 i9505

**Comment by sorano** [comment] 2015-09-24 11:48
Duplicate of #205

**Closed by sorano** 2015-09-24 11:48 UTC
