### ISSUE TITLE
Force close app and MAC recognition problem

### ISSUE THREAD

**Issue by mcilya** [cSploit/android#372] opened 2015-10-05 08:38 UTC
Android 4.4.2, Samsung Galaxy Note 2, Csploit-nightly (downloaded at 18:02 GMT+10)
How to reproduce: 
Force close: Launch cSploit -> wait till it scan for hosts -> cSploit closes
MAC problem: Launch cSploit -> wait till it scan for hosts -> Look at MAC address (For me it was "Xerox")
Catlog: http://pastebin.com/jxBCpdra
Screenshot of MAC problem:
![2015-10-05 18 36 36](https://cloud.githubusercontent.com/assets/6566449/10276065/cc25e0e4-6b87-11e5-86e8-b29adefd3f8d.png)

**Comment by tux-mind** [comment] 2015-10-05 15:06
for the force close it seems to be and [android system bug](https://code.google.com/p/android/issues/detail?id=188607&thanks=188607&ts=1444052638).

you can temporary work around it by manually install latest release.

working on the other one.

**Comment by Tajnymag** [comment] 2015-10-05 16:10
I'm also seeing everyone as Xerox :)

**Comment by tux-mind** [comment] 2015-10-05 16:16
@Tajnymag can you confirm that the MAC address bug is present on nightly and **not** from 1.6.0 ? thank you in advance ;)

**Comment by xaitax** [comment] 2015-10-05 16:47
I can confirm it for the nightly.

**Comment by Tajnymag** [comment] 2015-10-05 17:33
Yes, I confirm the bug on latest nightly

**Closed** 2015-10-06 09:42 UTC

**Comment by tux-mind** [comment] 2015-10-06 09:45
mumble mumble... still fail

**Comment by sorano** [comment] 2015-10-06 09:48
do you want a [Mumble] server for csploit so we can talk with voip?
[Mumble]:
http://wiki.mumble.info/wiki/Main_Page

**Comment by tux-mind** [comment] 2015-10-06 09:51
mumble mumble stands for "thinking hard"

![mumble](http://www.audiocentralmagazine.com/wp-content/uploads/2013/09/mumble.jpg)

:wink:

**Comment by sorano** [comment] 2015-10-06 09:54
Yeah I know mate, I was just pulling your leg ;)
Will stop spamming now. Sorry to all who received  mails.

**Comment by mcilya** [comment] 2015-10-06 10:24
Now it doesnt crashes but it shows all MACs as "Xerox"
