### ISSUE TITLE
Ruby update issue

### ISSUE THREAD

**Issue by loganrussell48** [cSploit/android#227] opened 2015-08-31 19:43 UTC
There is currently an issue where Ruby doesn't update correctly on my LG G Pad 8.3 

To describe the issue, when i open the app, it tells me there is an update available for Ruby(whether or not there actually is an update, I'm not sure). I allow it to update, it downloads the file, checks the file, and right after it begins the extracting stage, it fails and no update is installed.

**Comment by hightechstl** [comment] 2015-08-31 19:44
This is a known issue and is currently being worked on

**Comment by sorano** [comment] 2015-09-24 11:44
Duplicate of #205

**Closed by sorano** 2015-09-24 11:44 UTC
