### ISSUE TITLE
Cant start service inspector

### ISSUE THREAD

**Issue by dustinwho** [cSploit/android#546] opened 2015-12-22 18:04 UTC
I can get into the "tab" itself ,but the blue play button isn't clickable

**Comment by pahapoika** [comment] 2015-12-23 08:49
Try nightly build. http://rootbitch.cc/csploit/cSploit-nightly.apk

**Comment by DPFH** [comment] 2015-12-23 09:14
Same problem, same solution.
However msf won't install in nightly, so I installed stable, installed msf, upgraded to nightly.

**Comment by pahapoika** [comment] 2015-12-23 09:35
Nightly is now 1.7.0 unstable so it doesnt matter if you first install stable and then upgrade it to nightly cuz nightly is 1.7.0 unstable as i said. @tux-mind could told peoples to install the nightly if normal is not working in readme

**Comment by pahapoika** [comment] 2015-12-23 09:38
And @dustinwho you could check the issues cuz theres 3-people with same or almost same problem.

**Comment by DPFH** [comment] 2015-12-23 13:05
@pahapoika OT, how can I make metasploitable visible on my network? Virtualbox, host is debian 8 via wifi

**Comment by pahapoika** [comment] 2015-12-23 13:38
@DPFH it could be visible automatically but you can add it manually by pressing the +-icon and then just put the ip adress of metasploitable. But as i said i see the metaspoitable automatically when i start cSploit.

**Comment by pahapoika** [comment] 2015-12-23 14:09
@DDFH to see the metasploitables ip first login to console. Default username and password is msfadmin. Then just type ifconfig

**Comment by DPFH** [comment] 2015-12-23 14:32
The IP doesn't belong to my subnet, it isn't a csploit's issue but a problemi with the configuration of virtualbox :(

**Comment by pahapoika** [comment] 2015-12-24 05:31
So try run the metasploitable using WMware.
Im using WMware and it works perfectly.

**Comment by pahapoika** [comment] 2015-12-24 05:32
@DPFH

**Comment by tux-mind** [comment] 2015-12-24 06:59
Sorry for the late reply.
Can you reproduce the bug? How?

About cSploit versions: nightly isn't designed to solve bugs of the stable version, it's just a build of the development code.

There is a branch named "hotfix", which will be used to solve bugs of stable versions to release a minor update of the application ( say from 1.0.0 to 1.0.1 ).

So, no, installing the nightly is not the solution. 

Reporting the bug and help me improve the stable version is the solution :wink:

Thank you all for your patience and time :blush:

**Comment by tux-mind** [comment] 2015-12-24 17:55
Hi guys, I just tried out v1.6.2 ( current stable version ).

opened cSploit, selected a target and successfully performed an inspection...

I cannot reproduce the bug on my device. Anyone can spot the problem ?

I barely remember that there was a similar issue fixed by @fat-tire and @gustavo-iniguez-goya .

thank you all for your time :blush:

**Comment by pahapoika** [comment] 2015-12-24 17:56
@tux-mind i think this is common problem in kitkats. My samsung galaxy s4 (4.4.2)mini have the same problem. But nightly fix it. But my main phone oneplus 2 that runs cyanogenmod 12 (Lollipop) doesnt have that problem.

**Comment by BEOWULF74** [comment] 2015-12-24 17:57
I have this issue too in kitkat

**Comment by BEOWULF74** [comment] 2015-12-24 18:00
Just copy the code for inspection  from nightly to 1.6.2 cuz in nightly its working i think this is the fix for the problem cuz we cant give u log cuz theres not log

**Comment by tux-mind** [comment] 2015-12-24 18:38
Thanks you guys, I'll work on it tomorrow. I think that the problem can be
solved easily, just looking at the inspector sources history.

**Comment by DPFH** [comment] 2015-12-24 19:15
I have 4.1.2

**Comment by tux-mind** [comment] 2015-12-25 03:12
should be fixed in 1.6.3 .

please test out the [release candidate](https://github.com/cSploit/android/releases/tag/v1.6.3-rc.0) and tell me if the problem is solved.

thank you for your help :blush:

**Comment by BEOWULF74** [comment] 2015-12-25 03:17
I wish i can but i dont have wifi right now so i cant srry 😭😭 why i cant run csploit on data connection  😢😢

**Comment by pahapoika** [comment] 2015-12-25 06:15
@tux-mind works on my samsung galaxy s4 mini (4.4.2) 😄👌

**Comment by DPFH** [comment] 2015-12-25 07:38
Worked, both from upgrade and clean install!! ^^

**Comment by pahapoika** [comment] 2015-12-25 07:54
OT. Happy christmas everybody. 🎅

**Comment by DPFH** [comment] 2015-12-25 08:57
U 2

**Comment by tux-mind** [comment] 2015-12-25 09:50
fixed with [v1.6.3](https://github.com/cSploit/android/releases/tag/v1.6.3).
closing.


happy xmas :wink:
( sorry for the spoiler for who is < UTC-10 :grin: )

**Closed by tux-mind** 2015-12-25 09:50 UTC
Labels: bug, more info required, priority: high
