### ISSUE TITLE
Gem installation error. 

### ISSUE THREAD

**Issue by lief2** [cSploit/android#163] opened 2015-04-30 18:00 UTC
Like a lot of people, I have an error at the gems installation. I made a logcat and search the error, here is what I found:
E/CSPLOIT[core.UpdateService.execShell](16757): Gem::InstallError: metasploit-concern requires Ruby version >= 2.1.
I can't install msf because of this gem, help... 
I can give you the complete logcat if you want, ty.

**Comment by Azihak** [comment] 2015-05-06 07:44
Same problem here

**Comment by lief2** [comment] 2015-05-09 20:48
yeah, the nightly doesn't fix this error. I think that tux-mind is not available for now. Waiting...

**Comment by sorano** [comment] 2015-09-24 11:57
Duplicate of #205
Try the latest version.

**Closed by sorano** 2015-09-24 11:57 UTC
