### ISSUE TITLE
Service inspector button broke

### ISSUE THREAD

**Issue by Senkaaaa** [cSploit/android#459] opened 2015-10-21 00:27 UTC
Service inspector does not press on anything

Samsung galaxy s 5  4.4.2

Csploit 1.6.2

**Comment by sorano** [comment] 2015-10-21 07:41
You need to attach logs in order for us to help.

This is also duplicate of #452

**Closed by sorano** 2015-10-21 07:41 UTC
Labels: duplicate

**Comment by gainan** [comment] 2015-10-21 07:51
Hey @Senkaaaa , it should be fixed on the [latest nightly](http://rootbitch.cc/csploit/cSploit-nightly.apk). Try it out again and let us know if it works.
