### ISSUE TITLE
MFS update failed

### ISSUE THREAD

**Issue by bossco79** [cSploit/android#152] opened 2015-04-22 10:45 UTC
Hi man!
Help me in my trouble pls.
Catlog: https://www.dropbox.com/s/kp3zyuuveu25pxf/2015-04-22-07-19-44.txt?dl=0
Device Meizu mx4, FlymeOS 3.7.3

**Comment by sorano** [comment] 2015-09-24 11:47
Duplicate of #205

**Closed by sorano** 2015-09-24 11:47 UTC
