### ISSUE TITLE
обновление Ruby

### ISSUE THREAD

**Issue by Volufe32** [cSploit/android#153] opened 2015-04-22 11:54 UTC
При попытке обновить Ruby выдает ошибку.

**Comment by CoolOppo** [comment] 2015-04-22 15:14
Are you completely oblivious to the fact that this is an english-speaking website?

**Comment by Volufe32** [comment] 2015-04-23 04:24
Ok, My problem is that Ruby is not updated.
I went in and he told me cSploit proposes to update Ruby, wait 2-3 minutes and then gives an error.

**Comment by sorano** [comment] 2015-09-24 11:47
Duplicate of #205

**Closed by sorano** 2015-09-24 11:47 UTC
