### ISSUE TITLE
Failing to install ruby gems

### ISSUE THREAD

**Issue by MuradTroll** [cSploit/android#218] opened 2015-08-13 23:48 UTC
First of all I am so glad someone tries to keep dsploit up. 

The problem is that when installing ruby gems I get an error. Now I cannot provide a logcat, but the logcat said something about

HTTP 502 Error gems.dsploit.net

Or similar. This is because the gem server is not running which leads to a faulty installation. Trying to run metasploit rpcd logcat sais that some gems are missing.

 Could anyone provide the full data of release 1.5.3? I mean the msf and ruby folder and stuff.

**Comment by Rubenoo** [comment] 2015-08-14 09:36
This could be the reason why the gems are failing to update because they cant get any gems because the server is down. @tux-mind Can you take a look at this?

**Comment by MuradTroll** [comment] 2015-08-14 09:47
As far as I know dsploit used a system called "gem in a box"
Using this, you can host your own server with all the gems needed.
But since the server is down, we need to download the gems from another server
(Either the official rubygems server or a new gem in the box server)

An easier way would be hosting the full msf and ruby data
This should provide full service, even if some servers are down.
The only problem is that this method would not be so efficient, because the user would have to download about 150 mb data.

Thats how I understood it works.

**Comment by MuradTroll** [comment] 2015-08-14 11:36
#205 they have the same problem I think
 The question is, if this problem is a downloading problem caused by server down or if this is another problem...

**Comment by DeveloppSoft** [comment] 2015-08-14 13:43
Thanks, we are already working on it

**Comment by MuradTroll** [comment] 2015-08-14 15:06
@DeveloppSoft
I read your other posts and I am very glad to see that there are people who try to help and contribute to this project in any way.

Can you tell me what solution you are thinking of? I mean hosting a new gemserver or rewriting the programm?

**Comment by fat-tire** [comment] 2015-08-16 17:49
FWIW, and I haven't talked to @tux-mind about it, but the problem does seem to be that dsploit.net doesn't have a gems server any more, and UpdateService.java still uses:

**Comment by MuradTroll** [comment] 2015-08-16 23:15
@fat-tire
Why do they have to set up a special server for gems? Cant they just download it from official rubygems repo?

**Comment by MuradTroll** [comment] 2015-08-18 09:43
@fat-tire why not downloading the gems from rubygems official repo? So just change the REMOTE_GEM_SERVER

**Comment by DeveloppSoft** [comment] 2015-08-18 12:08
I think downloading a custom archive with all the dependicies

**Comment by tux-mind** [comment] 2015-08-20 12:11
yep, I'm working on changing the way we install gems.
we will ship an MSF tarball with native gems included and patched Gemfile
and specs.
in this way cSploit don't have to patch the MSF code ( just a little ) and
will not install native gems from remote.

I'm sorry for taking so long but I've also to finish a website for
September.

I'll keep you posted.

**Comment by hightechstl** [comment] 2015-08-20 12:17
Hurray! Thank you for letting us know you are working on it. Scary, I was
about to install zAnti when I received this email... It's like you knew.....

**Comment by DeveloppSoft** [comment] 2015-08-21 11:12
Good @tux-mind, we all support you

**Comment by DeveloppSoft** [comment] 2015-08-21 11:12
Good @tux-mind, we all support you

**Comment by jellium** [comment] 2015-08-24 16:56
Thanks for the heads-up and great work @tux-mind.

**Comment by sorano** [comment] 2015-09-24 11:45
Duplicate of #205

**Closed by sorano** 2015-09-24 11:45 UTC
