### ISSUE TITLE
Cannot start process

### ISSUE THREAD

**Issue by jeancarlosg93** [cSploit/android#76] opened 2015-02-13 00:45 UTC
Csploit 1.4.1
Cm12 android 5.0.2
One plus one (bacon)

Errors when dowloading core update and metasploitframework
Cannot start inspector

**Comment by mcilya** [comment] 2015-02-13 00:49
Can you post logcat and /data/data/org.csploit.android/files/csploitd.log

**Comment by jeancarlosg93** [comment] 2015-02-13 01:48
Here are the logs you requested http://goo.gl/MI1GzV

**Comment by mcilya** [comment] 2015-02-13 02:38
You're affected by #1 there is no solution right now. Msf doesnt updates for me so youre not alone :wink:

**Comment by jeancarlosg93** [comment] 2015-02-13 03:21
Ok, thanks for the info ☺

**Comment by sorano** [comment] 2015-09-24 12:05
Duplicate of #205
Try the latest version.

**Closed by sorano** 2015-09-24 12:05 UTC
