### ISSUE TITLE
MSF Update fails !

### ISSUE THREAD

**Issue by sudodevil** [cSploit/android#224] opened 2015-08-22 03:43 UTC
At the point "installing gemz for MSF" update always fails and metasploit server can't start anymore. Whats wrong?

**Comment by DeveloppSoft** [comment] 2015-08-24 06:54
We are already working on it

**Comment by Rubenoo** [comment] 2015-08-24 06:55
@developpSoft do you guys have a ETA?

**Comment by DeveloppSoft** [comment] 2015-08-26 13:22
@Rubenoo, please, what does 'ETA' mean ?

**Comment by Rubenoo** [comment] 2015-08-26 13:27
D

**Comment by Rubenoo** [comment] 2015-08-26 13:28
@developpSoft it means :"Estimated Time of Arrival" , I wanted to know if you guys know when the msf is working again, like next week or something

**Comment by Rubenoo** [comment] 2015-08-26 14:25
@developpSoft it means :"Estimated Time of Arrival" , I wanted to know if you guys know when the msf is working again, like next week or something

**Comment by DeveloppSoft** [comment] 2015-08-28 06:42
I do not know, @tux-mind is trying to downgrading msf.
For the moment, I am working on an other solution wich will work well with cSploit, and my Linux Distro

**Comment by Rubenoo** [comment] 2015-08-28 06:46
@developpSoft Can you notice everyone if you find the solution? And thank you for helping tuxmind with this project

**Comment by DeveloppSoft** [comment] 2015-08-31 14:08
Yes, of course

**Comment by sorano** [comment] 2015-09-24 11:50
Duplicate of #205

**Closed by sorano** 2015-09-24 11:50 UTC
