### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by WolfServer** [cSploit/android#411] opened 2015-10-10 17:27 UTC
A quick suggestion: how about support for Bluetooth hacking?

**Comment by Tajnymag** [comment] 2015-10-10 19:10
I'm not sure but think it was already suggested earlier. Anyway, I would also love to see it implemented :)

**Comment by Rubenoo** [comment] 2015-10-10 19:14
duplicate of #312 Close please

**Closed** 2015-10-10 20:38 UTC
