### ISSUE TITLE
compile the tools with PIE

### ISSUE THREAD

**Issue by norbertc** [cSploit/android#18] opened 2014-11-09 16:19 UTC
This is to support upcoming Android 5.0 Lollipop, wherein position-independent executable is now mandatory.

**Comment by erionialb** [comment] 2015-01-08 21:54
This is a problem with android 5.0, must flash this file on recovery that u can download from here : "http://forum.xda-developers.com/attachment.php?attachmentid=3061976&d=1418466953"
. before doing this you must completely delete csploit and all his component. it will help with the sniffing and Heart attack. enjoy

**Comment by tux-mind** [comment] 2015-01-12 18:54
@erionialb that method is just a workaround.
i'll provide a copy of the binaries that work on PIE-only devices.

**Comment by tux-mind** [comment] 2015-01-29 23:41
duplicate of #24 

btw i've fixed it on my N4, I need some days to write a new way to ship core executables.

**Closed by tux-mind** 2015-01-29 23:41 UTC
Labels: bug
