### ISSUE TITLE
Cannot update ruby

### ISSUE THREAD

**Issue by asms** [cSploit/android#182] opened 2015-06-09 19:08 UTC
Promped with:
"An update for ruby is available, do you want to download it?" Options: No, Yes

Selecting "Yes" results in:
"An error occurred while downloading the update."

**Comment by asms** [comment] 2015-06-09 19:10
Model: SM-G900T
Android 5.0

**Comment by sorano** [comment] 2015-09-24 11:58
Duplicate of #205
Try the latest version.

**Closed by sorano** 2015-09-24 11:58 UTC
