### ISSUE TITLE
Service inspector

### ISSUE THREAD

**Issue by Darkblade621** [cSploit/android#548] opened 2015-12-23 22:02 UTC
Service inspector does not work.

**Comment by pahapoika** [comment] 2015-12-24 07:27
@Darkblade621 Theres 4-issues with same problem. You should first read them and then ask. But install nightly it should solve the problem http://rootbitch.cc/csploit/cSploit-nightly.apk

**Comment by tux-mind** [comment] 2015-12-24 15:41
duplicate of #546 

thank you for pointing it out @pahapoika :blush:

**Closed by tux-mind** 2015-12-24 15:41 UTC
