### ISSUE TITLE
Installing gems.... stuck

### ISSUE THREAD

**Issue by Peruna** [cSploit/android#191] opened 2015-06-22 11:17 UTC
Stuck when installing gems.... Help!

**Comment by Lrs121** [comment] 2015-06-22 16:06
Issue reports like this are not helpful. This is not a help request thread this is for reporting issues and helping to resolve them. Please enable logging in the settings and post the log as well as a logcat from the process.

**Comment by sorano** [comment] 2015-09-24 11:52
Duplicate of #205

**Closed by sorano** 2015-09-24 11:52 UTC
