### ISSUE TITLE
cSploit can't extract msf.tar.xz in Android 6, Nexus 6

### ISSUE THREAD

**Issue by WoolF911** [cSploit/android#503] opened 2015-11-15 06:18 UTC
java.lang.RuntimeException: cannot install msf gems
	at org.csploit.android.services.UpdateService.installGems(UpdateService.java:873)
	at org.csploit.android.services.UpdateService.onHandleIntent(UpdateService.java:953)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by WoolF911** [comment] 2015-11-15 06:21
java.lang.RuntimeException: cannot install msf gems
	at org.csploit.android.services.UpdateService.installGems(UpdateService.java:873)
	at org.csploit.android.services.UpdateService.onHandleIntent(UpdateService.java:953)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by Taomyn** [comment] 2015-11-16 21:05
I'm having the same issue, same error and same phone/OS. Fresh install of the app, so no previous one to cause problems.

Have tried deleting the downloaded archive file but the issue happens again. Other updates it downloaded worked fine.

**Comment by WoolF911** [comment] 2015-11-16 21:13
I tried some of the previous versions of the night build — the problem was the same.
It seems to me that the system can not unpack this type of file.

**Comment by gainan** [comment] 2015-11-16 22:12
Hi @WoolF911 , @Taomyn , thank you for the report! could you please post full logcat?
https://github.com/cSploit/android/wiki/How-to-open-an-issue

Thanks in advance!

**Comment by unixasaurusrex** [comment] 2015-11-16 22:13
I'm having the same problem on my nexus 6p.

**Comment by WoolF911** [comment] 2015-11-16 22:36
Logcat


[2015-11-17_01-33-35.log.txt](https://github.com/cSploit/android/files/36053/2015-11-17_01-33-35.log.txt)

**Comment by Pieniasty** [comment] 2015-11-16 23:23
I also have this problem on my Nexus 4 with unofficial 6.0 rom (Chroma).

**Comment by codebam** [comment] 2015-11-17 05:48
Same here.

log: https://www.dropbox.com/s/6wxea1j9xto6c8l/2015-11-17_00.22-msf_gems.zip?dl=0

**Comment by Lypsis** [comment] 2015-11-19 00:47
Same Problem with Android 6.0 (MRA58N) on my Nexus 5 with cSploit app version from F-Droid.

**Comment by Lypsis** [comment] 2015-11-19 01:32
This entry shows up as an error in logcat:

11-19 02:25:55.060 16714 21596 E CSPLOIT[services.UpdateService.execShell]: running: bundle install --verbose --local --gemfile '/data/user/0/org.csploit.android/files/msf/Gemfile' --without development test

**Comment by fat-tire** [comment] 2015-11-25 09:55
This seems to be issue in @WoolF911 logcat:
~~~~
parse_cmd: parsing "rm -rf '/data/user/0/org.csploit.android/files/ruby/lib/ruby/gems/1.9.1/cache/'"
E/01:33:26.706 CSPLOIT[core.System.errorLogging](21031)
	at android.os.HandlerThread.run(HandlerThread.java:61)
E/01:33:26.706 CSPLOIT[core.System.errorLogging](21031)
	at android.os.Looper.loop(Looper.java:148)
E/01:33:26.706 CSPLOIT[core.System.errorLogging](21031)
	at android.os.Handler.dispatchMessage(Handler.java:102)
E/01:33:26.706 CSPLOIT[core.System.errorLogging](21031)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
E/01:33:26.706 CSPLOIT[core.System.errorLogging](21031)
	at org.csploit.android.services.UpdateService.onHandleIntent(UpdateService.java:953)
E/01:33:26.706 CSPLOIT[core.System.errorLogging](21031)
	at org.csploit.android.services.UpdateService.installGems(UpdateService.java:873)
E/01:33:26.706 CSPLOIT[core.System.errorLogging](21031)
java.lang.RuntimeException: cannot install msf gems
E/01:33:26.706 CSPLOIT[core.System.errorLogging](21031)
cannot install msf gems
~~~

That error references [here](https://github.com/cSploit/android/blob/develop/cSploit/src/main/java/org/csploit/android/services/UpdateService.java#L886), line 886.

Question-- what happens if you try to do this manually from the command line as root:

      # rm -rf '/data/user/0/org.csploit.android/files/ruby/lib/ruby/gems/1.9.1/cache/

I'm curious about the `/data/user/0/`... usually that's just `/data/data/org.csploit...`  Did something change in marshmallow where these files are stored?  It should default to:

    return mContext.getFilesDir().getAbsolutePath() + "/ruby";

If this absolute path changed from `/data/data/...` to `/data/user/0/...` after an update from lollipop->marshmallow, the hard-coded absolute path name would be wrong,  A fix to this would be to clear settings in cSploit and try again to see if it finds the right place...  this is just a theory but if anyone can try it, let me know.  Also what happens if you try to remove it manually?

**Comment by Taomyn** [comment] 2015-11-25 10:05
I executed the "rm" command and no error was returned.

The "/0" folder is correct for Marshmallow and I believe also for Lollipop but I think MM enforces it. The folder is to cater for multi-user I believe.

I installed cSploit direct to MM on my Nexus 6, so I never upgraded.

**Comment by PixelPips** [comment] 2015-11-25 18:36
MSF downloads, but once it's finished "extracting", it just tells me there was an error downloading.

Info:

Phone Type: Nexus 5
OS: Marshmallow 6.0 (rooted)
Kernel version: 3.4.0-g0acc96d
Rom: Chroma (can't find version number)
cSploit Version: v1.6.2
MSF Branch: csploit
Logcat (grep -i "csploit"): http://pips.rocks/sGpW

Anyone know what's going on? It'd be nice to test MSF out on a Metasploitable device.

**Comment by tux-mind** [comment] 2015-11-26 10:11
problem is the new android openssl library, fixing ...

**Comment by fat-tire** [comment] 2015-11-26 10:14
thanks @tux-mind !

**Comment by Taomyn** [comment] 2015-11-26 10:21
@tux-mind great find

**Comment by tux-mind** [comment] 2015-11-27 00:36
fixed in [version 1.0.5](https://github.com/cSploit/android.native.ruby/releases/tag/v1.0.5).

please update also the core to [version 1.0.9](https://github.com/cSploit/android.native/releases/tag/v1.0.9) that solve the same bug on our used tools.

please give me a feedback as I don't have a 6.0 device.

**Comment by PixelPips** [comment] 2015-11-27 06:29
Well, that didn't work. I will post a full error log in a few minutes, but a few things to note:
* If you change the `MSF directory` to, lets say, `/sdcard/csploit/` (it's own folder), and it fails, it deletes EVERYTHING IT CAN ON /SDCARD/. All of it.
    * Creating a test directory in `/sdcard/`: http://pips.rocks/o0Nl
    * After the download failed: http://pips.rocks/U57d

Bye-bye images, downloads, backups, etc.

**Comment by PixelPips** [comment] 2015-11-27 06:51
Fresh install, and fresh /sdcard/ (thanks to it wiping the entire dir)

Logcat: http://pips.rocks/D7VR

**Comment by fat-tire** [comment] 2015-11-27 07:03
I'm guessing it has to do with [this line](https://github.com/cSploit/android/blob/develop/cSploit/src/main/java/org/csploit/android/services/UpdateService.java#L225).  Are you sure the directory was set to `/sdcard/csploit/` and not `/sdcard/` ?  Or maybe you put a space in there or something?

In any event, I do think using `rm -rf [variable]` could use some checks or something.  Not sure exactly the best way to handle it if you want to wipe everything in the msfdir... maybe just delete the specific file...

**Comment by tux-mind** [comment] 2015-11-27 09:57
@PixelPips I'm truly sorry for the issue.

first of all let me help you get back your data.

read the section `read from good` of [this article](http://lifeinarootshell.blogspot.co.il/2013/10/disaster-recovery-on-android-phones.html) to make an image of your sdcard on your computer.
read [this article](https://github.com/ameer1234567890/OnlineNandroid/wiki/How-To-Gather-Information-About-Partition-Layouts) to find out your partition names. take care of retrieving only useradata.

after that you can recover your data using photorec.

working on the issue anyway.

**Comment by tux-mind** [comment] 2015-11-27 10:04
@PixelPips , your logcat is incomplete, can you reproduce it again and capture another one ?

thank you

**Comment by tux-mind** [comment] 2015-11-27 10:40
just thinking...

in v1.6.2 there is 4 write usage of field outputDir of the Update class.

one is in the Update#reset method, which will set it to null, called only by the Update constructor.

other 3 are in:

  - `CoreUpdate` contructor
  - `RubyUpdate` contructor
  - `MsfUpdate` contructor

so the outputDir field is immutable.

the wipe function will exit immediately, doing nothing, if Update.outputDir is null, so it cannot be null.

the Update instance that is managed during the installation process will not be overwritten as the only write usage is in the top of onHandleIntent ( checkme: can onHandleIntent called more than once on the same instance ? ).

if our `rm -rf` fails a java version will be called, not on outputDir but on `new File(outputDir)`.
this is probably the problem.

have to go now, will keep working on it ASAP.

**Comment by PixelPips** [comment] 2015-11-27 17:28
The logcat I posted was just for the MSF download error, showing that the new core and gems (and MSF) don't install correctly.

Sadly, I wasn't able to get the logcat from when `/sdcard/` was wiped. I can try and re-create the error, but it looks like you might already know what caused it.

**Comment by tux-mind** [comment] 2015-11-27 18:36
@PixelPips no, I didn't found the issue yet... can you reproduce and post a logcat again ?

if you cannot get the logcat because it get cancelled from sdcard I believe that you can save it after the issue with catlog.

from your logs it should be impossible that cSploit wiped your sdcard, but I believe you, so let's find out where the problem is :wink:

**Comment by PixelPips** [comment] 2015-11-27 19:15
That log I posted has nothing to do with the wipe, as I said, I wasn't able to get a logcat when it wiped. The log was just echoing this issue, that MSF and Gems won't install.

It didn't wipe the entire SD card (obviously), but it wiped `/sdcard/`/`/storage/emulated/0/`

The issue happened when I changed the MSF directory. I'll try and recreate it, but I'd rather not have it wipe `/sdcard/`again.

**Comment by tux-mind** [comment] 2015-11-27 23:05
Forgive me, I misunderstood your previous posts.

I'll look in the right direction now, thanks for your patience and report :)

About the installation problem: working on...
I'll try to download an android 6.0 image to perform some test myself.

**Comment by tux-mind** [comment] 2015-11-27 23:52
@PixelPips found the wipe problem.

it's reproducible in the following way:

  - settings
  - MSF directory
  - click on the bottom blue button ( selecting your sdcard )
  - click on MSF directory again
  - choose to restore the default path
  - answer yes to cancel previous directory location

A prompt has been presented to you and you choose to wipe the previous location, which was your sdcard.

the only thing I can do is to write the path that cSploit will delete within that prompt... 

according to the v1.6.2 sources a wipe can be triggered from settings only after user confirmation when he [changes the current directory](https://github.com/cSploit/android/blob/v1.6.2/cSploit/src/org/csploit/android/SettingsActivity.java#L171) or when he [click on delete MSF](https://github.com/cSploit/android/blob/v1.6.2/cSploit/src/org/csploit/android/SettingsActivity.java#L157).

do you confirm it ?

**Comment by tux-mind** [comment] 2015-11-28 07:47
I got my android 6.0 emulator :blush: 

must go to the office, writing here for later reference.

```
LoadError: dlopen failed: cannot locate symbol "SSLv2_method" referenced by "/data/data/ruby/lib/ruby/1.9.1/arm-linux-androideabi/openssl.so"... - /data/data/ruby/lib/ruby/1.9.1/arm-linux-androideabi/openssl.so
        from /data/data/ruby/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /data/data/ruby/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /data/data/ruby/lib/ruby/1.9.1/openssl.rb:17:in `<top (required)>'
        from /data/data/ruby/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /data/data/ruby/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from (irb):1
        from /data/data/ruby/bin/irb:12:in `<main>'
```

**Comment by tux-mind** [comment] 2015-11-30 00:00
ruby package version 1.0.6, manually installed, works good on android 6.0 emulator.

feel free to reopen this issue if needed :wink:

**Closed by tux-mind** 2015-11-30 00:00 UTC
