### ISSUE TITLE
Ruby, Msf

### ISSUE THREAD

**Issue by Marenel** [cSploit/android#147] opened 2015-04-18 14:07 UTC
After download Ruby appear error "Can't start the process"

**Comment by Systemad** [comment] 2015-04-18 14:40
This is not problem

**Comment by Marenel** [comment] 2015-04-18 15:06
Ok, and after unarchiving msf about 97% appear "An error occurred while updating". Sorry for my bad english

**Comment by sorano** [comment] 2015-09-24 11:48
Duplicate of #205

**Closed by sorano** 2015-09-24 11:48 UTC
