### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Agent47ua** [cSploit/android#816] opened 2017-01-16 08:17 UTC
java.lany.NullPointenException: Attempt to invoke virtual method ' void org.csploit.android.MainActivity$TargetAdapter.notifDataSetChardet ( )' on a null object reterence

Lenovo P70-A
Android 5.1
KingRoot

**Comment by pahapoika** [comment] 2017-01-16 11:34
KingRoot is no no.
Use supersu instead

**Comment by pahapoika** [comment] 2017-02-03 14:02
Closing since no answer in 18-days and because error caused by incompatibility.

**Closed by pahapoika** 2017-02-03 14:02 UTC
