### ISSUE TITLE
nokogiri gem

### ISSUE THREAD

**Issue by Duartebm** [cSploit/android#139] opened 2015-04-06 09:40 UTC
The ruby gems always crashes on the instalation on a gem called nokogiri. Please help. I use a dg350, rooted, full busybox pro.

**Comment by Duartebm** [comment] 2015-04-06 09:43
Btw, I have android 4.2.9 and the latest csploit version

**Comment by sorano** [comment] 2015-09-24 11:49
Duplicate of #205

**Closed by sorano** 2015-09-24 11:49 UTC
