### ISSUE TITLE
Nightly Build link is broken

### ISSUE THREAD

**Issue by uranium-waffles** [cSploit/android#243] opened 2015-09-14 22:28 UTC
When i click the nightly build link it redirects me to yahoo can someone test it and see if it works for them?

**Comment by GhostSamurai** [comment] 2015-09-15 03:15
Yea its been doing that too me for a while now

**Comment by xaitax** [comment] 2015-09-15 13:35
Fixed. I just had the webserver off for about 24h. All good again.

**Comment by hightechstl** [comment] 2015-09-15 14:17
Nightly build does not work anyway. Installed but won't open. It tries to
open but immediately closes.

**Comment by Rubenoo** [comment] 2015-09-15 14:28
Yeah it crashed by me to when I open it :/
Op 15 sep. 2015 16:18 schreef "hightechstl" <notifications@github.com>:

> Nightly build does not work anyway. Installed but won't open. It tries to
> open but immediately closes.

**Comment by evertking** [comment] 2015-09-15 15:16
Crashes for me too. Does anyone have the https http redirect patch in zip format?

**Comment by gainan** [comment] 2015-09-15 15:53
Maybe the crash is due to the bug that @fat-tire fixed (#133). Could someone gather adb logs and paste them to pastebin?

@evertking that fix will only add a redirection rule to iptables, but won´t enable/fix https interception yet due to some problems (it's disabled by code and the session hijacker module does not handle https connections). I´ve got another fix for that, which I´ll post soon.

**Comment by uranium-waffles** [comment] 2015-09-16 02:38
@hightechstl  i had the same problem i was just about to ask if anyone else had issues

**Comment by GRSteelers** [comment] 2015-09-16 14:29
Logcat with install followed by attempting to open: http://pastebin.com/NKvx64rR
HTC One m8 on a custom Sense ROM.

**Comment by gainan** [comment] 2015-09-16 14:52
@GRSteelers this is why the app is crashing:
>Caused by: java.lang.NullPointerException: Null pointer exception during instruction 'monitor-enter >v1'org.csploit.android.core.System.registerSettingListener(System.java:512)

this problem was fixed with one change of this commit: #133 , but it´s not present on the released apk yet.

**Comment by GRSteelers** [comment] 2015-09-16 16:07
That was 6 months ago. This issue is about the nightly build.
On Sep 16, 2015 10:52 AM, ga <notifications@github.com> wrote:@GRSteelers this is why the app is crashing:


Caused by: java.lang.NullPointerException: Null pointer exception during instruction 'monitor-enter >v1'org.csploit.android.core.System.registerSettingListener(System.java:512)


this problem was fixed with one change of this commit: #133 , but it´s not present on the released apk yet.

**Comment by xaitax** [comment] 2015-09-17 06:34
Because the pull requests wasn't commit to the repo yet @GRSteelers.

**Comment by Tajnymag** [comment] 2015-09-17 06:39
Exactly! Just commit those half-year old pull requests to the main repo :D

**Closed** 2015-09-18 02:57 UTC
