### ISSUE TITLE
no sirve

### ISSUE THREAD

**Issue by caceres82** [cSploit/android#877] opened 2017-06-02 17:01 UTC
##DEVICE:RYXIfv2vHIrd7hmk

##OS version:

##cSploit version:

##busybox (installed or not):

##Rooted with supersu?

##logcat (filter it!):

**Daemon specific questions**

##Go version:

##OS:

##Using Docker (incase of unofficial build.)

##Actions performed:

#Logs:

##Issue:
*Remember to search for issues alike before creating new one.

**Comment by Silur** [comment] 2017-06-19 16:26
duplicate of #876

**Closed as completed by Silur** 2017-06-19 16:26 UTC
Labels: duplicate
