### ISSUE TITLE
MSFRPC Error downloading update.

### ISSUE THREAD

**Issue by Msrpc** [cSploit/android#77] opened 2015-02-13 02:08 UTC
cSploit:1.4.1
Samsung Galaxy S3 CM12 Lollipop 5.0.2

"cannot start process"
"Error:An error occurred while downloading the update." 

cSploit debug:http://pastebin.com/Nuuqwz7r

catlog:http://pastebin.com/N34tsZye

**Comment by rigid** [comment] 2015-02-15 08:59
same here on CM11

**Comment by tux-mind** [comment] 2015-02-21 19:44
Duplicate of #43

**Closed by tux-mind** 2015-02-21 19:44 UTC
