### ISSUE TITLE
Heart attack ocurred

### ISSUE THREAD

**Issue by KatsuShooter** [cSploit/android#765] opened 2016-11-01 13:27 UTC
Hi. I have Meizu pro 6. I installed root from settings because kingoroot doesn't work. So I installed csploit yesterday too. It worked good. But today when I get upped and opened csploit I saw text "heart attack occurred etc. " if do you know answer write please!

**Comment by IwraStudios** [comment] 2016-11-01 14:45
make sure you have the latest version of busybox and cSploit
also could you supply some more info

**Comment by KatsuShooter** [comment] 2016-11-01 16:19
I update but I have that problem. In nightly version it's work, but it's not found devices. I saw my telephone and router.

**Comment by IwraStudios** [comment] 2016-11-01 18:15
and does the newest RC (https://github.com/cSploit/android/releases) not work?

**Comment by KatsuShooter** [comment] 2016-11-02 03:32
No

**Comment by pannzh** [comment] 2016-11-13 09:08
This problem is caused by KingUser or KingRoot. You may want to replace it with SuperSU or other root permission managers.

**Comment by pahapoika** [comment] 2017-02-03 11:10
Closing since duplicated.
All futher messages should be sent in
#828

**Closed by pahapoika** 2017-02-03 11:10 UTC
