### ISSUE TITLE
please help me :(

### ISSUE THREAD

**Issue by zardanadam** [cSploit/android#39] opened 2014-12-27 21:12 UTC
p}
[DEBUG  ] send_message: message sent (fd=2)
[DEBUG  ] send_message: { seq = 3, size = 12, id = 2, data = '\x00\x00\x05\x00.h\x00\x00\x0A$\x06e' }
[DEBUG  ] send_message: message sent (fd=2)
[DEBUG  ] send_message: { seq = 4, size = 12, id = 2, data = '\x00\x00\x07\x00\x88c\x00\x00\x0A$SV' }
[DEBUG  ] send_message: message sent (fd=2)
[DEBUG  ] send_message: { seq = 2, size = 6, id = 0, data = '\x07\x00\x02\x00\x00\x00' }
[DEBUG  ] reaper: thread "handle_child(name=nmap, pid=18563)" joined. (exit_val=0x0, tid=10021280)
[ERROR  ] read_wrapper: read: Connection reset by peer
[DEBUG  ] reaper: thread "handle_child(name=raw, pid=18347)" joined. (exit_val=0x0, tid=10022200)
[DEBUG  ] reaper: thread "connection_worker" joined. (exit_val=0x0, tid=10020112)
[ERROR  ] write_wrapper: write: Broken pipe
[ERROR  ] connection_writer: cannot send the following message
[DEBUG  ] connection_writer: { seq = 3, size = 167, id = 0, data = '\x09\x00\x01\x00/data/data/org.csploit.android/files/msf/metasploit-framework.gemspec:27: warning: Insecure world writable dir /data/data/org.csploit.android in PATH, mode 040773\x00' }
[ERROR  ] write_wrapper: write: Bad file number
[ERROR  ] connection_writer: cannot send the following message
[DEBUG  ] connection_writer: { seq = 4, size = 100, id = 0, data = '\x09\x00\x01\x00WARNING: Nokogiri was built against LibXML version 2.7.8, but has dynamically loaded 20708.3.58\x00' }
[ERROR  ] write_wrapper: write: Bad file number
[ERROR  ] connection_writer: cannot send the following message
[DEBUG  ] connection_writer: { seq = 5, size = 8, id = 0, data = '\x08\x00\x01\x00\x0F\x00\x00\x00' }
[DEBUG  ] connection_reader: connection closed (fd=2)
[DEBUG  ] reaper: thread "connection_writer" joined. (exit_val=0x0, tid=10019528)
[DEBUG  ] reaper: thread "connection_reader" joined. (exit_val=0x0, tid=10020696)
[DEBUG  ] connection_reader: started (fd=1, tid=10020696)
[DEBUG  ] connection_worker: started (fd=1, tid=10020112)
[DEBUG  ] connection_writer: started (fd=1, tid=10019528)
[DEBUG  ] read_message: received a message (fd=1)
[DEBUG  ] read_message: { seq = 0, size = 18, id = 0, data = '\x00android\x00DEADBEEF\x00' }
[DEBUG  ] on_auth_request: user "android" logged in
[DEBUG  ] send_message: message sent (fd=1)
[DEBUG  ] send_message: { seq = 0, size = 1, id = 0, data = '\x01' }
[DEBUG  ] read_message: received a message (fd=1)
[DEBUG  ] read_message: { seq = 1, size = 1, id = 0, data = '\x0A' }
[DEBUG  ] send_message: message sent (fd=1)
[DEBUG  ] send_message: { seq = 1, size = 75, id = 0, data = '\x0A\x03\x02ettercap\x00\x05\x02arpspoof\x00\x07\x02fusemounts\x00\x01\x03raw\x00\x02\x02nmap\x00\x00\x00blind\x00\x06\x02tcpdump\x00\x04\x02hydra\x00' }
[DEBUG  ] read_message: received a message (fd=1)
[DEBUG  ] read_message: { seq = 2, size = 851, id = 0, data = '\x03\x01\x0Emsfrpcd\x00-P\x00msf\x00-U\x00msf\x00-p\x005553\x00-a\x00127.0.0.1\x00-n\x00-S\x00-t\x00Msg\x00-f\x00RUBYLIB=/data/data/org.csploit.android/files/ruby/lib/ruby/site_ruby/1.9.1:/data/data/org.csploit.android/files/ruby/lib/ruby/site_ruby/1.9.1/arm-linux-androideabi:/data/data/org.csploit.android/files/ruby/lib/ruby/site_ruby:/data/data/org.csploit.android/files/ruby/lib/ruby/vendor_ruby/1.9.1:/data/data/org.csploit.android/files/ruby/lib/ruby/vendor_ruby/1.9.1/arm-linux-androideabi:/data/data/org.csploit.android/files/ruby/lib/ruby/vendor_ruby:/data/data/org.csploit.android/files/ruby/lib/ruby/1.9.1:/data/data/org.csploit.android/files/ruby/lib/ruby/1.9.1/arm-linux-androideabi\x00PATH=/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin:/data/data/org.csploit.android/files/ruby/bin:/data/data/org.csploit.android/files/msf\x00HOME=/data/data/org.csploit.android/files/ruby/home/ruby\x00' }
[DEBUG  ] on_cmd_start: successfully started a child for 'raw' (pid=18653)
[DEBUG  ] send_message: message sent (fd=1)
[DEBUG  ] send_message: { seq = 2, size = 4, id = 0, data = '\x04\x00\x01\x00' }
[DEBUG  ] handle_child: new child started. (name=raw, pid=18653)
[DEBUG  ] read_message: received a message (fd=1)
[DEBUG  ] read_message: { seq = 3, size = 70, id = 0, data = '\x03\x02\x06-sn\x00--traceroute\x00--privileged\x00--send-ip\x00--system-dns\x00192.168.1.156\x00' }
[DEBUG  ] on_cmd_start: successfully started a child for 'nmap' (pid=18792)
[DEBUG  ] send_message: message sent (fd=1)
[DEBUG  ] send_message: { seq = 3, size = 4, id = 0, data = '\x04\x00\x02\x00' }
[DEBUG  ] handle_child: new child started. (name=nmap, pid=18792)
[DEBUG  ] send_message: message sent (fd=1)
[DEBUG  ] reaper: thread "handle_child(name=nmap, pid=18792)" joined. (exit_val=0x0, tid=10021280)
[DEBUG  ] send_message: { seq = 2, size = 6, id = 0, data = '\x07\x00\x02\x00\x00\x00' }
[DEBUG  ] read_message: received a message (fd=1)
[DEBUG  ] read_message: { seq = 4, size = 48, id = 0, data = '\x03\x01\x03sh\x00-c\x00echo 0 > /proc/sys/net/ipv4/ip_forward\x00' }
[DEBUG  ] read_message: received a message (fd=1)
[DEBUG  ] read_message: { seq = 5, size = 8, id = 0, data = '\x06\x00\x01\x00\x02\x00\x00\x00' }
[DEBUG  ] on_cmd_start: successfully started a child for 'raw' (pid=18843)
[DEBUG  ] send_message: message sent (fd=1)
[DEBUG  ] handle_child: new child started. (name=raw, pid=18843)
[DEBUG  ] send_message: { seq = 4, size = 4, id = 0, data = '\x04\x00\x03\x00' }
[DEBUG  ] send_message: message sent (fd=1)
[DEBUG  ] send_message: { seq = 3, size = 6, id = 0, data = '\x07\x00\x03\x00\x00\x00' }
[DEBUG  ] reaper: thread "handle_child(name=raw, pid=18843)" joined. (exit_val=0x0, tid=10021280)
[DEBUG  ] reaper: thread "handle_child(name=raw, pid=18653)" joined. (exit_val=0x0, tid=10022224)
[DEBUG  ] send_message: message sent (fd=1)
[DEBUG  ] send_message: { seq = 4, size = 167, id = 0, data = '\x09\x00\x01\x00/data/data/org.csploit.android/files/msf/metasploit-framework.gemspec:27: warning: Insecure world writable dir /data/data/org.csploit.android in PATH, mode 040773\x00' }
[ERROR  ] write_wrapper: write: Bad file number
[ERROR  ] connection_writer: cannot send the following message
[DEBUG  ] connection_writer: { seq = 5, size = 100, id = 0, data = '\x09\x00\x01\x00WARNING: Nokogiri was built against LibXML version 2.7.8, but has dynamically loaded 20708.3.58\x00' }
[ERROR  ] write_wrapper: write: Bad file number
[ERROR  ] connection_writer: cannot send the following message
[DEBUG  ] connection_writer: { seq = 6, size = 8, id = 0, data = '\x08\x00\x01\x00\x0F\x00\x00\x00' }
[DEBUG  ] connection_reader: connection closed (fd=1)
[DEBUG  ] reaper: thread "connection_worker" joined. (exit_val=0x0, tid=10020112)
[DEBUG  ] reaper: thread "connection_writer" joined. (exit_val=0x0, tid=10019528)
[DEBUG  ] reaper: thread "connection_reader" joined. (exit_val=0x0, tid=10020696)

**Comment by tux-mind** [comment] 2015-01-12 13:00
Hi @zardanadam thanks for the log.
can you explain what are the bad behaviour ?

post also the logcat ( you posted only the daemon log ).

thanks for your contribute.

**Comment by tux-mind** [comment] 2015-01-28 13:22
duplicate of #40

**Closed by tux-mind** 2015-01-28 13:22 UTC
Labels: more info required
