### ISSUE TITLE
msfrpcd port problem

### ISSUE THREAD

**Issue by greensmith** [cSploit/android#89] opened 2015-02-24 11:45 UTC
Hello

I tried to connect to the msf rpc daemon from another machine - but couldnt.
I tried changing the port to see if that resolved the issue, and am now having a different one.

**ps aux | grep msfrpcd**  returns the following

**ruby /storage/sdcard0/meta/msfrpcd -P msf -U msf -p 8080 -a 127.0.0.1 -n -S -t Msg -f**

The port I chose was not 8080, however every time I change the port, stop and restart the MSRPCD, it reverts to port 8080...

**netstat** shows nothing listening on 8080 even when **ps aux** shows it is running.

**Comment by greensmith** [comment] 2015-02-24 12:15
I've also tried manually editing the shared prefs xml file.

But it does not seem to be reading this.

**Comment by sorano** [comment] 2015-09-24 14:51
Duplicate of #122

**Closed by sorano** 2015-09-24 14:51 UTC
Labels: duplicate
