### ISSUE TITLE
failing ruby and msf install

### ISSUE THREAD

**Issue by stgrosso** [cSploit/android#155] opened 2015-04-23 14:30 UTC
While updating csploit the ruby process can't start and eventually the msf gems wont get msf installed returning an error messahe after a little while.
Issue on faced on the following devices:
Xperia z1 lollipo
Nexus 7 kitkat
Hope you can help
Thanks

**Comment by sorano** [comment] 2015-09-24 11:47
Duplicate of #205

**Closed by sorano** 2015-09-24 11:47 UTC
