### ISSUE TITLE
Ruby fails to unpack

### ISSUE THREAD

**Issue by raynommo** [cSploit/android#51] opened 2015-01-30 03:59 UTC
I can't get csploit to work on samsung note 3, it downloads ruby, but does not install it. I tried to put ruby in csploit files folder, but no success either.

[DEBUG  ] connection_writer: started (fd=1, tid=29729384)
[DEBUG  ] connection_worker: started (fd=1, tid=29729968)
[DEBUG  ] connection_reader: started (fd=1, tid=29730552)
[DEBUG  ] read_message: received a message (fd=1)
[DEBUG  ] read_message: { seq = 0, size = 18, id = 0, data = '\x00android\x00DEADBEEF\x00' }
[DEBUG  ] on_auth_request: user "android" logged in
[DEBUG  ] send_message: message sent (fd=1)
[DEBUG  ] send_message: { seq = 0, size = 1, id = 0, data = '\x01' }
[DEBUG  ] read_message: received a message (fd=1)
[DEBUG  ] read_message: { seq = 1, size = 1, id = 0, data = '\x0A' }
[DEBUG  ] send_message: message sent (fd=1)
[DEBUG  ] send_message: { seq = 1, size = 91, id = 0, data = '\x0A\x06\x02tcpdump\x00\x01\x03raw\x00\x02\x02nmap\x00\x08\x02network-radar\x00\x04\x02hydra\x00\x07\x02fusemounts\x00\x03\x02ettercap\x00\x00\x00blind\x00\x05\x02arpspoof\x00' }
[DEBUG  ] read_message: received a message (fd=1)
[DEBUG  ] read_message: { seq = 2, size = 9, id = 0, data = '\x03\x08\x01wlan0\x00' }
[ERROR  ] on_cmd_start: execvp: Permission denied
[DEBUG  ] on_cmd_start: { seq = 2, size = 9, id = 0, data = '\x03\x08\x01wlan0\x00' }
[DEBUG  ] send_message: message sent (fd=1)
[DEBUG  ] send_message: { seq = 2, size = 1, id = 0, data = '\x05' }
[DEBUG  ] read_message: received a message (fd=1)
[DEBUG  ] read_message: { seq = 3, size = 851, id = 0, data = '\x03\x01\x0Emsfrpcd\x00-P\x00msf\x00-U\x00msf\x00-p\x005553\x00-a\x00127.0.0.1\x00-n\x00-S\x00-t\x00Msg\x00-f\x00RUBYLIB=/data/data/org.csploit.android/files/ruby/lib/ruby/site_ruby/1.9.1:/data/data/org.csploit.android/files/ruby/lib/ruby/site_ruby/1.9.1/arm-linux-androideabi:/data/data/org.csploit.android/files/ruby/lib/ruby/site_ruby:/data/data/org.csploit.android/files/ruby/lib/ruby/vendor_ruby/1.9.1:/data/data/org.csploit.android/files/ruby/lib/ruby/vendor_ruby/1.9.1/arm-linux-androideabi:/data/data/org.csploit.android/files/ruby/lib/ruby/vendor_ruby:/data/data/org.csploit.android/files/ruby/lib/ruby/1.9.1:/data/data/org.csploit.android/files/ruby/lib/ruby/1.9.1/arm-linux-androideabi\x00PATH=/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin:/data/data/org.csploit.android/files/ruby/bin:/data/data/org.csploit.android/files/msf\x00HOME=/data/data/org.csploit.android/files/ruby/home/ruby\x00' }
[ERROR  ] on_cmd_start: execvp: Permission denied
[DEBUG  ] on_cmd_start: { seq = 3, size = 851, id = 0, data = '\x03\x01\x0Emsfrpcd\x00-P\x00msf\x00-U\x00msf\x00-p\x005553\x00-a\x00127.0.0.1\x00-n\x00-S\x00-t\x00Msg\x00-f\x00RUBYLIB=/data/data/org.csploit.android/files/ruby/lib/ruby/site_ruby/1.9.1:/data/data/org.csploit.android/files/ruby/lib/ruby/site_ruby/1.9.1/arm-linux-androideabi:/data/data/org.csploit.android/files/ruby/lib/ruby/site_ruby:/data/data/org.csploit.android/files/ruby/lib/ruby/vendor_ruby/1.9.1:/data/data/org.csploit.android/files/ruby/lib/ruby/vendor_ruby/1.9.1/arm-linux-androideabi:/data/data/org.csploit.android/files/ruby/lib/ruby/vendor_ruby:/data/data/org.csploit.android/files/ruby/lib/ruby/1.9.1:/data/data/org.csploit.android/files/ruby/lib/ruby/1.9.1/arm-linux-androideabi\x00PATH=/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin:/data/data/org.csploit.android/files/ruby/bin:/data/data/org.csploit.android/files/msf\x00HOME=/data/data/org.csploit.android/files/ruby/home/ruby\x00' }
[DEBUG  ] send_message: message sent (fd=1)
[DEBUG  ] send_message: { seq = 3, size = 1, id = 0, data = '\x05' }
[DEBUG  ] read_message: received a message (fd=1)
[DEBUG  ] read_message: { seq = 4, size = 13, id = 0, data = '\x03\x01\x02which\x00env\x00' }
[ERROR  ] on_cmd_start: execvp: Permission denied
[DEBUG  ] on_cmd_start: { seq = 4, size = 13, id = 0, data = '\x03\x01\x02which\x00env\x00' }
[DEBUG  ] send_message: message sent (fd=1)
[DEBUG  ] send_message: { seq = 4, size = 1, id = 0, data = '\x05' }
[DEBUG  ] read_message: received a message (fd=1)
[DEBUG  ] read_message: { seq = 5, size = 52, id = 0, data = '\x03\x01\x03rm\x00-rf\x00/data/data/org.csploit.android/files/ruby\x00' }
[ERROR  ] on_cmd_start: execvp: Permission denied
[DEBUG  ] on_cmd_start: { seq = 5, size = 52, id = 0, data = '\x03\x01\x03rm\x00-rf\x00/data/data/org.csploit.android/files/ruby\x00' }
[DEBUG  ] send_message: message sent (fd=1)
[DEBUG  ] send_message: { seq = 5, size = 1, id = 0, data = '\x05' }
[DEBUG  ] read_message: received a message (fd=1)
[DEBUG  ] read_message: { seq = 6, size = 94, id = 0, data = '\x03\x01\x04du\x00-xsm\x00/data/data/org.csploit.android/files/ruby\x00/data/data/org.csploit.android/files/msf\x00' }
[ERROR  ] on_cmd_start: execvp: Permission denied
[DEBUG  ] on_cmd_start: { seq = 6, size = 94, id = 0, data = '\x03\x01\x04du\x00-xsm\x00/data/data/org.csploit.android/files/ruby\x00/data/data/org.csploit.android/files/msf\x00' }
[DEBUG  ] send_message: message sent (fd=1)
[DEBUG  ] send_message: { seq = 6, size = 1, id = 0, data = '\x05' }

**Comment by mcilya** [comment] 2015-01-30 04:52
i think you have #1

**Comment by raynommo** [comment] 2015-01-30 05:18
I have tried many builds, same error. SuperSU or Superuser, same error. BusyBox or BusyBox on rails, no luck. Selinux in permissive, fail. Running out of ideas(

**Comment by raynommo** [comment] 2015-01-30 05:20
Even moved csploit to system/app through Lucky Patcher. No result

**Comment by Interneedus** [comment] 2015-01-30 07:28
Are you on KK?

**Comment by raynommo** [comment] 2015-01-30 07:36
Yep 4.4.2

**Comment by Interneedus** [comment] 2015-01-30 07:42
Is your SD Card properly writable?

**Comment by raynommo** [comment] 2015-01-30 07:45
I don't know, how can I check that? Every other app that requires root run fine

**Comment by Interneedus** [comment] 2015-01-30 08:11
Can non-root apps write to your SD Card? Like can PowerAMP delete .mp3 that are on your SD Card?

**Comment by raynommo** [comment] 2015-01-30 08:17
Yes, it can.

**Comment by tux-mind** [comment] 2015-02-01 13:33
@raynommo you're affected by #1 

I have to get my paws on an affected device to fix it.
currently I'm working on fixing android 5, after that i will focus on #1 .

it seems that only samsung kernels are affected.

duplicate of #1

**Closed by tux-mind** 2015-02-01 13:33 UTC
