### ISSUE TITLE
new 1.4.3 update crash

### ISSUE THREAD

**Issue by TheRollingEdit** [cSploit/android#90] opened 2015-02-25 21:45 UTC
Csploit worked fine in its last update which fixed the msf download issue, now, on 1.4.3, it says Csploit has stoped working. I am on a nexus 6 with cm12. If you need a logcat, just ask me.

**Comment by Wym0n** [comment] 2015-02-25 22:36
I'm having the same issue, stock nexus 6

Logcat: http://pastebin.com/iFwX31Nx

**Comment by Settix** [comment] 2015-02-25 23:06
Yup,  same thing for me ( stock 4.4.4, xperia z3) and on n9 too

**Comment by alexmanner** [comment] 2015-02-26 00:43
Same for me :-)

**Comment by xDragonZ** [comment] 2015-02-26 04:20
Here's the log

02-26 12:18:36.956 E/CSPLOIT[core.System.errorLogging](26041): java.lang.NullPointerException
02-26 12:18:36.956 E/CSPLOIT[core.System.errorLogging](26041): java.lang.NullPointerException
02-26 12:18:36.956 E/CSPLOIT[core.System.errorLogging](26041): 	at org.csploit.android.core.ExecChecker.canExecuteInDir(ExecChecker.java:248)
02-26 12:18:36.956 E/CSPLOIT[core.System.errorLogging](26041): 	at org.csploit.android.tools.Ruby.setEnabled(Ruby.java:48)
02-26 12:18:36.956 E/CSPLOIT[core.System.errorLogging](26041): 	at org.csploit.android.tools.Ruby.<init>(Ruby.java:37)
02-26 12:18:36.956 E/CSPLOIT[core.System.errorLogging](26041): 	at org.csploit.android.tools.ToolBox.<init>(ToolBox.java:41)
02-26 12:18:36.956 E/CSPLOIT[core.System.errorLogging](26041): 	at org.csploit.android.core.System.init(System.java:153)
02-26 12:18:36.956 E/CSPLOIT[core.System.errorLogging](26041): 	at org.csploit.android.CSploitApplication.onCreate(CSploitApplication.java:54)
02-26 12:18:36.956 E/CSPLOIT[core.System.errorLogging](26041): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
02-26 12:18:36.956 E/CSPLOIT[core.System.errorLogging](26041): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4473)
02-26 12:18:36.956 E/CSPLOIT[core.System.errorLogging](26041): 	at android.app.ActivityThread.access$1500(ActivityThread.java:144)
02-26 12:18:36.956 E/CSPLOIT[core.System.errorLogging](26041): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
02-26 12:18:36.956 E/CSPLOIT[core.System.errorLogging](26041): 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-26 12:18:36.956 E/CSPLOIT[core.System.errorLogging](26041): 	at android.os.Looper.loop(Looper.java:136)
02-26 12:18:36.956 E/CSPLOIT[core.System.errorLogging](26041): 	at android.app.ActivityThread.main(ActivityThread.java:5146)
02-26 12:18:36.956 E/CSPLOIT[core.System.errorLogging](26041): 	at java.lang.reflect.Method.invokeNative(Native Method)
02-26 12:18:36.956 E/CSPLOIT[core.System.errorLogging](26041): 	at java.lang.reflect.Method.invoke(Method.java:515)
02-26 12:18:36.956 E/CSPLOIT[core.System.errorLogging](26041): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
02-26 12:18:36.956 E/CSPLOIT[core.System.errorLogging](26041): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
02-26 12:18:36.956 E/CSPLOIT[core.System.errorLogging](26041): 	at dalvik.system.NativeStart.main(Native Method)
02-26 12:18:36.966 E/AndroidRuntime(26041): FATAL EXCEPTION: main
02-26 12:18:36.966 E/AndroidRuntime(26041): Process: org.csploit.android, PID: 26041
02-26 12:18:36.966 E/AndroidRuntime(26041): java.lang.RuntimeException: Unable to create application org.csploit.android.CSploitApplication: java.lang.NullPointerException
02-26 12:18:36.966 E/AndroidRuntime(26041): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4476)
02-26 12:18:36.966 E/AndroidRuntime(26041): 	at android.app.ActivityThread.access$1500(ActivityThread.java:144)
02-26 12:18:36.966 E/AndroidRuntime(26041): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
02-26 12:18:36.966 E/AndroidRuntime(26041): 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-26 12:18:36.966 E/AndroidRuntime(26041): 	at android.os.Looper.loop(Looper.java:136)
02-26 12:18:36.966 E/AndroidRuntime(26041): 	at android.app.ActivityThread.main(ActivityThread.java:5146)
02-26 12:18:36.966 E/AndroidRuntime(26041): 	at java.lang.reflect.Method.invokeNative(Native Method)
02-26 12:18:36.966 E/AndroidRuntime(26041): 	at java.lang.reflect.Method.invoke(Method.java:515)
02-26 12:18:36.966 E/AndroidRuntime(26041): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
02-26 12:18:36.966 E/AndroidRuntime(26041): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
02-26 12:18:36.966 E/AndroidRuntime(26041): 	at dalvik.system.NativeStart.main(Native Method)
02-26 12:18:36.966 E/AndroidRuntime(26041): Caused by: java.lang.NullPointerException
02-26 12:18:36.966 E/AndroidRuntime(26041): 	at org.csploit.android.core.System.registerPlugin(System.java:1139)
02-26 12:18:36.966 E/AndroidRuntime(26041): 	at org.csploit.android.CSploitApplication.onCreate(CSploitApplication.java:62)
02-26 12:18:36.966 E/AndroidRuntime(26041): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
02-26 12:18:36.966 E/AndroidRuntime(26041): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4473)
02-26 12:18:36.966 E/AndroidRuntime(26041): 	... 10 more

**Comment by greensmith** [comment] 2015-02-26 16:14
Same here, downgrading for now.

**Comment by bionictrip** [comment] 2015-02-26 16:39
mKnownIssues = new KnownIssues();
in System.java needs to go before 
mTools = new ToolBox();

**Comment by xaitax** [comment] 2015-02-27 08:03
Can be closed. Issue not present anymore in current nightly.

**Comment by TheRollingEdit** [comment] 2015-02-27 11:17
The nightly still cant install msf, the nightly is unusable.

**Comment by Avamander** [comment] 2015-02-27 12:10
Cannot confirm LG D605 CM11

**Comment by xaitax** [comment] 2015-02-27 13:23
Just because you cannot install MSF doesn't mean this bug report is invalid. This issue for this ticket is fixed.

**Comment by tux-mind** [comment] 2015-03-26 20:39
sorry for the late reply

fixed in 853b32683b7618b4b5b7d45bfe3f48aab226483c

**Closed by tux-mind** 2015-03-26 20:39 UTC
