### ISSUE TITLE
Some issues with the current apk and builds

### ISSUE THREAD

**Issue by Cursewords** [cSploit/android#230] opened 2015-09-06 21:11 UTC
Phone: LG G4
OS: Android 5.1 (Rooted)
SELinux: Enforcing (I know it needs to be changed)

Whenever I try to download the Ruby package it fails with "An error occured while downloading the update". Could you please provide a fix for this?

Also the nightly build won't even open on my phone. It just opens and then closes immediately.

Is this project still open? If so I will definitely consider a donation as the other project zANTI2 is over a year old and hasn't been made open source, nor available for personal download which I think is absolutely terrible.

Thanks,
CW

**Comment by hightechstl** [comment] 2015-09-06 21:12
Yes it's still active. Tux-mind is currently working in a fix for this
issue.

**Comment by sorano** [comment] 2015-09-24 13:15
Duplicate of #205
Try the latest version. Ruby should be fixed.

@Cursewords 
tux_mind has recently started developing again.
Consider donating to keep the motivation up and help further development: http://www.csploit.org/donate.html

**Closed by sorano** 2015-09-24 13:15 UTC
