### ISSUE TITLE
gems fails to install

### ISSUE THREAD

**Issue by Wym0n** [cSploit/android#95] opened 2015-02-27 12:13 UTC
I have a nexus 6 5.0.1 lollipop and when gems goes to install I get the error that it failed to install.

**Comment by bionictrip** [comment] 2015-02-27 13:59
same or similar issue here oneplus one CM11 4.4.4
http://pastebin.com/fLSiTZKF

**Comment by ALoGeNo** [comment] 2015-02-27 15:53
Same here cm11  4.4.4, htc sensation

**Comment by bionictrip** [comment] 2015-02-27 16:39
was able to manually install mini_portile' (~> 0.5.0) 
gem install mini_portile -v '0.5.0' then gems installed successfully.

**Comment by strakplan** [comment] 2015-02-27 16:46
@bionictrip 

How did you installed it? Describe in detail steps please. Thanks.

**Comment by strakplan** [comment] 2015-02-27 16:57
I've almost same issue on CM12 nightly. After updating Ruby I get message "Cannot start process" and then cSploit ask me if I would like to update Metasploit Framework. When I touch on "Yes" it tries to install and then I get error message: "Error occured while downloading the update" 

And I think I'm not only one so please don't close this issue. 

Thanks.

**Comment by DominikTV** [comment] 2015-02-28 21:33
Same here, after a clean install, I can install the main core fine, the ruby says "cannot start process" after the download and the gms stays at "installing gems..." after the download until I cancel it.

Lollipop 5.0.1 Nexus 5

**Comment by MatthewHKnight** [comment] 2015-03-07 13:59
Having this same issue i left Installing gems for metasploit running for over 8 hours was still showing it was installing.
Nexus 7 2013 WiFi Tablet.

**Comment by MatthewHKnight** [comment] 2015-03-07 14:23
I think i might have figured out how to fix my problem what i did was is unchecked Enable MSF as the Installing gems for MSF was going that appears to have fixed that issue for me. You will need Put a Check mark back in the box if its able to install the gems to be able to use Metasploit RPCD.
Settings> Scroll down to Enable MSF uncheck box after installs gems finally place check back in that box Start Metasploit RPCD

**Comment by sorano** [comment] 2015-09-24 12:02
Duplicate of #205
Try the latest version.

**Closed by sorano** 2015-09-24 12:02 UTC
