### ISSUE TITLE
Service failed to start/failed update msf

### ISSUE THREAD

**Issue by hightechstl** [cSploit/android#222] opened 2015-08-16 05:11 UTC
Nexus 5 Pwn Phone 2014 build Android version 4.4.2

Updated core successful
Update Ruby: cannot start process
Update MetasploitFramework: An error occured while downloading the update (Fails at installing gems)
Port scanner working
Session Hijacker not working tested on multiple windows 7 desktops running google chrome and IE9 & 11

**Comment by MuradTroll** [comment] 2015-08-16 08:58
Same issue here. We have to wait devs are already working on it.

**Comment by DeveloppSoft** [comment] 2015-08-16 14:33
Yes, @tux-mind is downgrading msf for the moment

**Comment by MuradTroll** [comment] 2015-08-16 23:18
But will this fix the ruby gems server problem? I mean the older versions of msf are still dependent of rub gems bundles, right? I would suggest packing the gems right into the package instead of using a special bundler and server.

**Comment by DeveloppSoft** [comment] 2015-08-21 11:15
Maybe...

**Comment by sorano** [comment] 2015-09-24 11:45
Duplicate of #205

**Closed by sorano** 2015-09-24 11:45 UTC
