### ISSUE TITLE
csploit

### ISSUE THREAD

**Issue by gelero43** [cSploit/android#219] opened 2015-08-14 14:58 UTC
Metasploit dont start and port scanner dont find anything

**Comment by Rubenoo** [comment] 2015-08-15 09:03
the developers are aware of those bugs, please leave more detail about the bug. for example make a catlog ect

**Comment by DeveloppSoft** [comment] 2015-08-16 14:42
@Rubeeno, I totally agree with you.
@gelero23 and the others, please as you can see, we have a lot of issues like it, and... just one is needed, so do not reopen an issue, if you have something to add make a post into the issue

**Comment by sorano** [comment] 2015-09-24 11:40
Duplicate of #205

**Closed by sorano** 2015-09-24 11:40 UTC
