### ISSUE TITLE
MSF doesn't even attempt to download

### ISSUE THREAD

**Issue by evertking** [cSploit/android#527] opened 2015-12-06 17:46 UTC
When I installed the latest nightly on android 6.0 MSF does not even attempt to.download. I get the core 1.0.10? But that's it.

**Comment by BEOWULF74** [comment] 2015-12-10 02:11
Same here just installing core and then nothing happens android 4.4.2

**Comment by BEOWULF74** [comment] 2015-12-11 04:44
I know now what is the problem bro the start_daemon.sh doesn't start automatically so i have to start it manually fix it guys its really annoying thing

**Comment by tux-mind** [comment] 2015-12-25 10:18
duplicate of #532 

please move the conversation to #532 .

I need your logcat to find the bug and kill it, thank you in advance for your time :blush:

**Closed by tux-mind** 2015-12-25 10:18 UTC
