### ISSUE TITLE
Heart attack, pie

### ISSUE THREAD

**Issue by keaneokelley** [cSploit/android#42] opened 2015-01-02 16:54 UTC
I left this as a comment on a closed issue, but perhaps it should be a new one. I am still getting heart attack on the latest nightly and release, Nexus 5 on CM12. http://pastebin.com/hEumYbEX
I notice two things in this log: 1. The socket it is looking for does not exist (I double checked /dev/socket) 2. Only PIE execs are supported, meaning we can't just run a native binary out of any directory. This will be a problem for anybody on Android L.

**Comment by erionialb** [comment] 2015-01-08 21:51
This is a problem with android 5.0, must flash this file on recovery that u can download from here :                                                                                                                                         "http://forum.xda-developers.com/attachment.php?attachmentid=3061976&d=1418466953" 
                                                                                                                                                                .  before doing this you must completely delete csploit and all his component. it will help with the sniffing and Heart attack. enjoy

**Comment by keaneokelley** [comment] 2015-01-08 23:20
Yes, however that is a band-aid fix and device modifications as such should not be required for an app to work. There needs to be a better solution.

**Comment by erionialb** [comment] 2015-01-08 23:46
this is the only solution that i found for now and it is not only for csploit but for all the sniffing and spoofing tools that don't work on android 5.0 because of pie restriction.it's just until the kernel sorce will be dropt from google

**Comment by tux-mind** [comment] 2015-01-12 18:55
duplicate of #18 

@keaneokelley sorry for sending you many messages, but i read notifications by date :wink:

**Closed by tux-mind** 2015-01-12 18:55 UTC
