### ISSUE TITLE
force closing on gingerbread.

### ISSUE THREAD

**Issue by killoid** [cSploit/android#61] opened 2015-02-01 14:27 UTC
i've installed the latest stable release on my samsung galaxy y duos gt-s6102,running stock rooted gingerbread 2.3.6 rom. i've busybox v1.23.1-sterickson installed on my device. but when i try to open the app, it crashes. log is attached below.

E/20:19:56.625 AndroidRuntime( 4006)
	at org.csploit.android.core.Client.<clinit>(Client.java:10)
E/20:19:56.625 AndroidRuntime( 4006)
	at org.csploit.android.MainActivity$5.run(MainActivity.java:336)
E/20:19:56.625 AndroidRuntime( 4006)
	at org.csploit.android.core.ToolsInstaller.install(ToolsInstaller.java:85)
E/20:19:56.625 AndroidRuntime( 4006)
	at org.csploit.android.core.System.clean(System.java:1256)
E/20:19:56.625 AndroidRuntime( 4006)
	at org.csploit.android.core.System.setForwarding(System.java:1248)
E/20:19:56.625 AndroidRuntime( 4006)
	at org.csploit.android.tools.Shell.run(Shell.java:43)
E/20:19:56.625 AndroidRuntime( 4006)
	at org.csploit.android.tools.Shell.run(Shell.java:39)
E/20:19:56.625 AndroidRuntime( 4006)
	at org.csploit.android.tools.Raw.run(Raw.java:51)
E/20:19:56.625 AndroidRuntime( 4006)
	at org.csploit.android.tools.Tool.run(Tool.java:33)
E/20:19:56.625 AndroidRuntime( 4006)
	at org.csploit.android.tools.Tool.async(Tool.java:55)
E/20:19:56.625 AndroidRuntime( 4006)
	at org.csploit.android.core.ChildManager.async(ChildManager.java:81)
W/20:19:56.625 dalvikvm( 4006)
JNI_OnLoad returned bad version (-1) in /data/data/org.csploit.android/lib/libcSploitClient.so 0x407ac5d8
W/20:19:56.625 System.err( 4006)
	at org.csploit.android.MainActivity$5.run(MainActivity.java:336)
W/20:19:56.625 System.err( 4006)
	at org.csploit.android.core.ToolsInstaller.install(ToolsInstaller.java:85)
W/20:19:56.625 System.err( 4006)
	at org.csploit.android.core.System.clean(System.java:1256)
W/20:19:56.625 System.err( 4006)
	at org.csploit.android.core.System.setForwarding(System.java:1248)
W/20:19:56.625 System.err( 4006)
	at org.csploit.android.tools.Shell.run(Shell.java:43)
W/20:19:56.625 System.err( 4006)
	at org.csploit.android.tools.Shell.run(Shell.java:39)
W/20:19:56.625 System.err( 4006)
	at org.csploit.android.tools.Raw.run(Raw.java:51)
W/20:19:56.625 System.err( 4006)
	at org.csploit.android.tools.Tool.run(Tool.java:33)
W/20:19:56.625 System.err( 4006)
	at org.csploit.android.tools.Tool.async(Tool.java:55)
W/20:19:56.625 System.err( 4006)
	at org.csploit.android.core.ChildManager.async(ChildManager.java:81)
W/20:19:56.625 System.err( 4006)
	at org.csploit.android.core.Client.<clinit>(Client.java:10)
D/20:19:56.617 dalvikvm( 4006)
Added shared lib /data/data/org.csploit.android/lib/libcSploitClient.so 0x407ac5d8
D/20:19:56.593 dalvikvm( 4006)
Trying to load lib /data/data/org.csploit.android/lib/libcSploitClient.so 0x407ac5d8
D/20:19:56.546 dalvikvm( 4006)
No JNI_OnLoad found in /data/data/org.csploit.android/lib/libcSploitCommon.so 0x407ac5d8, skipping init
D/20:19:56.546 dalvikvm( 4006)
Added shared lib /data/data/org.csploit.android/lib/libcSploitCommon.so 0x407ac5d8
D/20:19:56.523 dalvikvm( 4006)
Trying to load lib /data/data/org.csploit.android/lib/libcSploitCommon.so 0x407ac5d8
D/20:19:56.523 CSPLOIT[core.ToolsInstaller.needed]( 4006)
Checking version file /data/data/org.csploit.android/files/tools/VERSION
I/20:19:55.632 ActivityManager( 1530)
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.csploit.android/.MainActivity } from pid 1614
I/20:19:49.195 InstallAppProgress( 3845)
Finished installing org.csploit.android
D/20:19:43.265 PackageManager( 1530)
Scanning package org.csploit.android

**Comment by mcilya** [comment] 2015-02-04 05:09
can you post /data/data/org.csploit.android/files/csploitd.log ?

**Comment by killoid** [comment] 2015-02-04 07:10
no csploit.log file is there.

**Comment by killoid** [comment] 2015-02-14 10:25
v1.4.1 is not working either. new log attached.

E/13:51:17.304 AndroidRuntime( 3494)
	at org.csploit.android.MainActivity.onCreate(MainActivity.java:353)
E/13:51:17.304 AndroidRuntime( 3494)
	at org.csploit.android.MainActivity.onInitializationError(MainActivity.java:247)
E/13:51:17.304 AndroidRuntime( 3494)
	at org.csploit.android.MainActivity$2.run(MainActivity.java:250)
E/13:51:17.304 AndroidRuntime( 3494)
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.csploit.android/org.csploit.android.MainActivity}: java.lang.NullPointerException
I/13:51:16.484 ActivityManager( 1530)
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.csploit.android/.MainActivity } from pid 1610
I/13:50:50.000 InstallAppProgress( 2992)
Finished installing org.csploit.android
D/13:50:43.843 PackageManager( 1530)
Scanning package org.csploit.android

**Comment by tux-mind** [comment] 2015-02-21 19:43
@killoid thanks for the report, can you post a full logcat? Thanks in advance.

**Comment by killoid** [comment] 2015-02-22 09:01
do you mean the system log? here you go. link: http://d-h.st/lYIU
btw i've tried v1.4.2 & it opened but showed a popup saying that core file is not installed & network is not connected. so do i have to open the app after turning on wifi?

**Comment by killoid** [comment] 2015-03-20 09:34
it force closes when i click ok on the following dialogue 'core file is not installed, a working network needed.' i enabled my mobile data & then it downloaded core file v1.0.4 but after that it force closed again. even when i click on settings within the app,it force closes. all this are on v1.5.0. new log attached. link: http://d-h.st/umou

**Comment by tux-mind** [comment] 2015-03-26 21:29
sorry for the late reply.
this seems a duplicate of #46 

can you try to uninstall/disable xposed to make a quick test ?

thanks in advance :blush:

**Comment by killoid** [comment] 2015-03-27 12:18
i've uninstalled xposed & tried above procedure. it still force closes. log - http://d-h.st/9DR5

**Comment by sorano** [comment] 2015-09-24 12:21
Older issue.
Try newer version with busybox installed in correct path and supersu. Then re-open and attach logs if you have further problems.

**Closed by sorano** 2015-09-24 12:21 UTC
Labels: bug, more info required
