### ISSUE TITLE
ruby update freezing on extracting

### ISSUE THREAD

**Issue by RaptorRebel21** [cSploit/android#434] opened 2015-10-15 00:23 UTC
What happening is that when I tap on update for ruby it downloads Then gets stuck on extracting. Also when I tap on a host (etc acer aspire) it freezes. Please help!

**Comment by gainan** [comment] 2015-10-15 07:46
First of all, thank you for reporting the bug @RaptorRebel21 . We need logs to see what's going on when the problem occurs. Please, take a moment to read this howto about how to give us more information of the bug: https://github.com/cSploit/android/wiki/How-to-open-an-issue

**Comment by sorano** [comment] 2015-10-21 19:50
User has not returned with any more info and I cannot reproduce the issue.
Lets close this.

**Closed by sorano** 2015-10-21 19:50 UTC
Labels: more info required
