### ISSUE TITLE
Gems not installing

### ISSUE THREAD

**Issue by Creativeusernam3** [cSploit/android#167] opened 2015-05-06 23:12 UTC
I'm new to the app, and the gems aren't installing to finish the mfc update. What can I do?

**Comment by Systemad** [comment] 2015-05-07 05:32
Nothing, you just have to wait until it's get fixed. And people should stop creating duplicate issues because it won't help.

**Comment by Creativeusernam3** [comment] 2015-05-07 05:34
Sorry if it was annoying, I just wasn't sure if anything was found
On May 6, 2015 10:32 PM, "Systemad" <notifications@github.com> wrote:
>
> Nothing, you just have to wait until it's get fixed. And people should
stop creating duplicate issues because it won't help.

**Comment by Systemad** [comment] 2015-05-07 06:44
@creativeusername3 I wasn't really pointing at just you :D, there are about 10 Topics on same issue...

**Comment by sorano** [comment] 2015-09-24 11:56
Duplicate of #205
Try the latest version.

**Closed by sorano** 2015-09-24 11:56 UTC
