### ISSUE TITLE
Completely freezes phone on large networks

### ISSUE THREAD

**Issue by GuilleDF** [cSploit/android#586] opened 2016-02-04 09:59 UTC
When the app is opened while on a network with many clients connected (50-60), the phone locks up almost completely, even when the app is running on the background

**Comment by fat-tire** [comment] 2016-02-11 04:32
Wonder if this is the port scan (1000 ports x 60 devices) getting overwhelmed... did you try turning that off to see if it makes a difference?  It's somewhere in the settings, i believe.  (I'm pretty sure csploit has been used on networks with hundreds or thousands of network devices so I'm not sure exactly..)

**Comment by GuilleDF** [comment] 2016-02-11 11:19
I tried with port scan disabled and it no longer freezes the whole phone, just the app itself. Maybe it's two different things?

**Comment by GuilleDF** [comment] 2016-02-11 11:20
Never mind, the application didn't freeze, it just took a really long time to load

**Comment by tux-mind** [comment] 2016-03-28 20:15
Closing, this issue is caused by a dummy use of nmap in our system, we don't use the network scan but spawn a process per host.

cSploit 2 will use nmap in a smarter way :blush:

**Closed by tux-mind** 2016-03-28 20:15 UTC
