### ISSUE TITLE
Installing MSF fails

### ISSUE THREAD

**Issue by Avamander** [cSploit/android#79] opened 2015-02-17 12:26 UTC
Device: LG D605
Software: CM11

Latest cSploit

https://www.dropbox.com/s/56ep5c02q223796/cSploitd.log?dl=1

**Comment by Interneedus** [comment] 2015-02-17 14:58
Duplicate of https://github.com/cSploit/android/issues/77

**Comment by tux-mind** [comment] 2015-02-21 19:50
Thanks for the report @Avamander and sorry for the late reply. Exams period.

Happy to have you on board again :blush: 

Duplicate of #43

**Closed by tux-mind** 2015-02-21 19:50 UTC
