### ISSUE TITLE
ruby cannot be installed on csploit

### ISSUE THREAD

**Issue by eggozaurus** [cSploit/android#216] opened 2015-08-12 11:32 UTC
I downloaded the metasploit framework but it must be buggy cause ruby failed to install please help

**Comment by Rubenoo** [comment] 2015-08-12 13:17
@eggozaurus the developers are already noticed of this bug, please look at the other problems to make sure that you don't post the same bug over and over again.

Please close

**Comment by sorano** [comment] 2015-09-24 11:46
Duplicate of #205

**Closed by sorano** 2015-09-24 11:46 UTC
