### ISSUE TITLE
problem with gems msf installation

### ISSUE THREAD

**Issue by bauermateus** [cSploit/android#144] opened 2015-04-10 13:56 UTC
hey, i'm not none expert in Android and nothing, but i want to help u and u help me... i updated core, ruby, and msf, but when finish extracting msf , it stuck on installing gems to MSF... can u help me? My phone is a motorola moto E xt1022

**Comment by bauermateus** [comment] 2015-04-10 13:57
Sorry for my bad english... I am brasilian

**Comment by Systemad** [comment] 2015-04-10 14:57
For long did you waited?
It can take up to 10 min. (It took 5 minutes for me)

**Comment by bauermateus** [comment] 2015-04-15 02:24
I waited 10 hours

**Comment by sorano** [comment] 2015-09-24 11:48
Duplicate of #205

**Closed by sorano** 2015-09-24 11:48 UTC
